---
# yamllint disable rule:line-length

name: tests

on:  # yamllint disable-line rule:truthy
  push:

paths-ignore:
  - "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
      - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8  # v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@559aa3035a47390ba96088dffa783b5d26da9326  # v1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
          toolchain: nightly
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3  # v2
        with:
          cache-on-failure: true
      - name: Build
        run: cargo build --verbose --locked

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
          toolchain: nightly
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3  # v2
        with:
          cache-on-failure: true
      - name: Run tests
        run: cargo test --verbose --locked

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
          toolchain: nightly
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3  # v2
        with:
          cache-on-failure: true
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
          toolchain: nightly
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3  # v2
        with:
          cache-on-failure: true
      - name: Install rustfmt
        run: rustup component add rustfmt
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5
        with:
          python-version: '3.x'
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
